server:
  port : 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver  # MySQL配置
    # mysql连接地址
    url: jdbc:mysql://localhost:3306/login_project?serverTimezone=GMT%2B8&&useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useSSL=false
    username: root # 账号
    password: root # 密码
  data:
    redis:
      port: 6379
      host: 127.0.0.1 # 191.168.253.129
    mongodb:
      port: 27017
      host: 192.168.253.129
      database: admin
      authentication-database: admin
      username: admin
      password: adminpwd
